version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
    - cluster.name=news-archives-cluster
    - node.name=news-archives-node
    - http.host=0.0.0.0
    - transport.host=0.0.0.0
    - transport.tcp.port=9300
    - transport.publish_port=9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
    - 9200:9200
    - 9300:9300
  news-archive-scrapper:
    build: newsarchivescrapper
    environment:
    - spring.data.elasticsearch.cluster-nodes=elasticsearch:9300
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
    volumes:
    - /news-archive-scrapper:/news-archive-scrapper
    ports:
    - 8080:8080
